[project]
name = "zcu"
version = "0.1.0"
description = "A collection of utility tools I frequently use for my work-related developments."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.2",
    "pywin32>=311",
    "xlwings>=0.35.3",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"zcu" = ["vba_src/*.bas", "vba_src/*.cls", "vba_src/*.frm"]